<a href="https://colab.research.google.com/github/Joycechidi/Secure-and-Private-AI/blob/master/build_private_database.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!conda create -n pysyft python=3

/bin/bash: conda: command not found


In [0]:
import torch

#the number of entries in out database
num_entries = 5000

db = torch.rand(num_entries) > 0.5
db

tensor([1, 0, 1,  ..., 1, 1, 1], dtype=torch.uint8)

Key to the definition of differential privacy is the ability to ask the question "
"When querying a database, If I removed someone from the database, would the output
of the query be different?". Thus, in order to check this, we must construct
what we term "parallel databases" which are simply databases with one entry removed.

# Task

Create a list of every parallel database to the one currently contained in the "db" variabl.
Then, create a function which both:
    1) creates the initial database (db)
    2) creates all parallel databases

In [0]:
db = torch.rand(num_entries) > 0.5
db
db.shape

torch.Size([5000])

To do this we have to first copy the database and then remove an entry by slicing off an entry before the one we want to remove and the entry after the one we want to remove. 

In [0]:
db[0:5] #this finds the 4th entry

tensor([1, 1, 0, 0, 0], dtype=torch.uint8)

In [0]:
remove_index = 2 #To slice off the 2nd index 

In [0]:
def get_parallel_db(db, remove_index):
  return torch.cat((db[0:remove_index],
                    db[remove_index+1:]))

In [0]:
get_parallel_db(db, 0).shape 
#this will show that one entry is removed because the count will reduce by 1.

torch.Size([4999])

Write a second function that will iterate over our database and create one of these parallel databases with that value removed.

In [0]:
parallel_dbs = list()

In [0]:
def get_parallel_dbs(db):
  
  parallel_dbs = list()


  for i in range(len(db)):
    pdb = get_parallel_db(db, i)
    parallel_dbs.append(pdb)
  
  return parallel_dbs

In [0]:
len(parallel_dbs)

0

In [0]:
pdbs = get_parallel_dbs(db)

In [0]:
def create_db_and_parallels(num_entries):
  
  db = torch.rand(num_entries) > 0.5
  pdbs = get_parallel_dbs(db)
  
  return db, pdbs

In [0]:
db, pdbs = create_db_and_parallels(20)

In [0]:
db

tensor([0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0],
       dtype=torch.uint8)

In [0]:
pdbs

[tensor([0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,