<a href="https://colab.research.google.com/github/Joycechidi/Secure-and-Private-AI/blob/master/intro_to_multi_layer_nn_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
def activation(x):
    """Sigmoid activation function
    
    Arguments
    ----------
    x: torch.Tensor
    
    """
    
    return 1/(1+torch.exp(-x))

In [0]:
#Generate some data 
torch.manual_seed(7) #Set the random seed so things are predictable

#Features are 3 random normal variabes
features = torch.randn((1, 3))

#Define the size of each layer in the network
n_input = features.shape[1] #Number of input units must match number of input features
n_hidden = 2                #Number of hidden units
n_output = 1                #Number of output units

#Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)

#Weights for inputs to hidden layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn(1, n_hidden)
B2 = torch.randn(1, n_output)



In [0]:
#Calculate the output this multi-layer network
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)

print(output)

tensor([[0.3171]])


# Numpy to Torch and back

In [0]:
import numpy as np

In [0]:
a = np.random.rand(4, 3)
a

array([[0.97272054, 0.15377103, 0.53827147],
       [0.47678645, 0.04123979, 0.06807873],
       [0.71509822, 0.77955059, 0.50191548],
       [0.79362112, 0.68391943, 0.71365048]])

In [0]:
b = torch.from_numpy(a)
b

tensor([[0.9727, 0.1538, 0.5383],
        [0.4768, 0.0412, 0.0681],
        [0.7151, 0.7796, 0.5019],
        [0.7936, 0.6839, 0.7137]], dtype=torch.float64)

In [0]:
b.numpy()

array([[0.97272054, 0.15377103, 0.53827147],
       [0.47678645, 0.04123979, 0.06807873],
       [0.71509822, 0.77955059, 0.50191548],
       [0.79362112, 0.68391943, 0.71365048]])

Remember here that the memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will changeas well.

Multiply PyTorch Tensor by 2, in place. 
This changes the value in memory. The values of the numpy array are changed by operations in the array. 
E.g Multipliction


In [0]:
b.mul_(2)

tensor([[3.8909, 0.6151, 2.1531],
        [1.9071, 0.1650, 0.2723],
        [2.8604, 3.1182, 2.0077],
        [3.1745, 2.7357, 2.8546]], dtype=torch.float64)