<a href="https://colab.research.google.com/github/Joycechidi/Secure-and-Private-AI/blob/master/intro_to_single_layer_nn_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#First import PyTorch
#!pip install torch

You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [0]:
import torch

In [0]:
def activation(x):
    """Sigmoid activation function
    
    Arguments
    ----------
    x: torch.Tensor
    
    """
    
    return 1/(1+torch.exp(-x))

In [0]:
#Generate some data 
torch.manual_seed(7) #Set the random seed so things are predictable

#Features are 5 random normal variabes
features = torch.randn((1, 5))
#True weights for our data, random normal variables again
weights = torch.randn_like(features)

#and a true bias term
bias = torch.randn((1, 1))
weights.reshape(5, 1)
weights.view(5, 1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [0]:
#Calculate the output of this single layer network using torch.sum()
y = activation(torch.sum(features * weights) + bias)
print(y)

y = activation((features * weights).sum() + bias)

tensor([[0.1595]])


In [0]:
#Calculate the output of this single layer network using matrix multiplication 
#The matrix multiplication is more efficient than the torch.sum

y = activation(torch.mm(features, weights.view(5, 1)) + bias)
print(y)

tensor([[0.1595]])
